// <auto-generated />
using System;
using Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Api.Migrations
{
    [DbContext(typeof(DefaultContext))]
    [Migration("20190723214540_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SimpleExampleApiNetCore.Api.Models.FundoCapital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DataResgate");

                    b.Property<string>("Nome");

                    b.Property<decimal>("ValorAtual");

                    b.Property<decimal>("ValorNecessario");

                    b.HasKey("Id");

                    b.ToTable("FundoCapital");
                });
#pragma warning restore 612, 618
        }
    }
}
